[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 14
#decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[terminal]

[terminal.shell]
program = "/bin/bash"
args = ["--login", "-c", "cd ~; exec /bin/bash"]

