tap "homebrew/bundle"
brew "fzf"
brew "git"
brew "luajit"
brew "neovim"
brew "rbenv"
brew "ripgrep"
brew "starship"
brew "utf8proc", args: ["HEAD"]
cask "alacritty"
cask "font-caskaydia-mono-nerd-font"
cask "google-drive"
cask "logseq"
cask "rectangle"
cask "spotify"
