# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character"""

# removed $kubernetes\ from top

[kubernetes]
format = '\([$symbol](blue)[$context](red)[:](white)$namespace\)'
disabled = false

[gcloud]
disabled = true

[line_break]
disabled = true

[character]
success_symbol = " [\\$](bold green)"

[package]
disabled = true

[directory]
style = ''

[git_branch]
style = 'green'
format = '[\($symbol$branch(:$remote_branch)\)]($style) '
